### ISSUE TITLE
Upload Videos 

### ISSUE THREAD

**Issue by griffynruiz** [griffynruiz/Downtown-Lubbock#1]
@jetercotton // **Due Date: Friday, November 15th**

We are needing to upload our most recent videos to the website. Each time I try to upload I am receiving this error message: 
<img width="879" alt="Screen Shot 2019-11-07 at 11 13 33 AM" src="https://user-images.githubusercontent.com/53316017/68413527-0de1bd80-0154-11ea-8ad2-52191d10af6a.png">

**Here are the log in credentials to the site:** 
https://downtownlbk.us/admin/login
**Username:** jerred@primitivesocial.com
**Password:** wp2937ymm#

**Here are the videos that need to be uploaded** 

**1 - First Friday Art Trail** 
Thumbnail: 
![DLBK_FFAT_Thumbnail](https://user-images.githubusercontent.com/53316017/68413794-919baa00-0154-11ea-956b-a0e3c4aec6d8.jpg)

Video: https://drive.google.com/drive/u/0/folders/1xdmDbCOZuLKs-EO1D73Y6FyLo3_A-sbN

**2 - Monomyth Coffee**
Thumbnail: 
![DLBK_Monomyth_Thumbnail](https://user-images.githubusercontent.com/53316017/68413878-c1e34880-0154-11ea-98f4-64f0fd4ecf35.jpg)

Video: https://drive.google.com/drive/u/0/folders/1o8sJirNMqdAjWsF52tVq6BKhOiK8kGIO

**3 - The Garden** 
Thumbnail: 
![DLBK_TheGarden_Thumbnail copy](https://user-images.githubusercontent.com/53316017/68413952-e17a7100-0154-11ea-9f15-569e082e5403.jpg)

Video: https://drive.google.com/drive/u/0/folders/1Db1wNgA-PgCvZMvxW2ygt1qKQsJjW5jw

Please let me know if you have any questions or if I can help in any way!

**Comment by jetercotton** [comment]
@griffynruiz Hey Griff! I just posted the first video, and didn't run into any troubles actually. Can you give me a call later today so I can run you through uploading the last two videos?

**Comment by griffynruiz** [comment]
🤦🏽‍♀️... I hate that I bothered you with it but I'm glad we got it figured out! i'll slack you so we can find a time. Thanks, jeter!

**Comment by jetercotton** [comment]
@griffynruiz It's not a bother at all! I guess I just scared it into working or something 😅

Yeah, just hmu and we can find a time to go through the last two vids.
